scrape_configs:
  # - job_name: 'prometheus'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['docker.for.mac.localhost:9090']
  #       labels:
  #         service: 'prometheus'
  #         group: 'production'

  - job_name: 'node-localhost'
    scrape_interval: 5s
    static_configs:
      - targets: ['docker.for.mac.localhost:4000']
        labels:
          service: 'node-app'
          group: 'production'

  - job_name: 'mysql'
    scrape_interval: 5s
    static_configs:
      - targets: ['docker.for.mac.localhost:9104']
        labels:
          service: 'mysql'
          group: 'production'
